// Code generated by mekami core-install; DO NOT EDIT.
//
// This file is the single source of truth for the set of language
// frontends the mekami binary blank-imports at startup. `mekami
// core-install <lang>` populates it from .mekami/config.json.
//
// This file is intentionally empty in the initial commit: the
// shipped CLI does not bundle any language frontend. After cloning,
// run `mekami core-install <lang>` to add the indexers your
// project needs; that command rewrites this file and updates
// .mekami/config.json.
package all_gen

import ()
