package coreinstall

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
)

// AllGenPath returns the absolute path of the generated
// all_gen.go file. In dev, this lives inside the mekami source
// tree (relative to the go.work file). In a production install
// (AUR), the file is part of the shipped binary's source tree
// and `core-install` cannot meaningfully rewrite it; we still
// write to the dev path for consistency, and the binary will
// not see the change until a rebuild. The dev-vs-prod
// distinction is documented in the package doc.
func AllGenPath(workDir string) string {
	return filepath.Join(workDir, "mekami-core", "frontend", "all_gen", "all_gen.go")
}

// FindWorkDir walks up from start looking for a go.work file.
// Returns the directory containing go.work, or an error if none
// is found up to the filesystem root.
func FindWorkDir(start string) (string, error) {
	dir, err := filepath.Abs(start)
	if err != nil {
		return "", err
	}
	for {
		candidate := filepath.Join(dir, "go.work")
		if info, err := os.Stat(candidate); err == nil && !info.IsDir() {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.work not found above %s", start)
		}
		dir = parent
	}
}

// GenerateAllGen renders the contents of all_gen.go from cfg's
// indexers map. Each entry produces a blank import for
// github.com/Wolf258/mekami-core-<name>. The Go toolchain reads
// the real version from mekami-cli/go.mod; the version in cfg is
// surfaced as a trailing comment for human readers.
//
// The output always includes a header marking the file as
// generated. The iteration is sorted by name so successive
// regenerations produce byte-identical files (the underlying map
// has undefined iteration order, but a stable sort is enough to
// keep `all_gen.go` free of spurious diffs). If the file
// already exists with the same contents WriteAllGen is a no-op
// on disk.
func GenerateAllGen(cfgIndexers map[string]string) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by mekami core-install; DO NOT EDIT.\n")
	buf.WriteString("//\n")
	buf.WriteString("// This file is the single source of truth for the set of language\n")
	buf.WriteString("// frontends the mekami binary blank-imports at startup. `mekami\n")
	buf.WriteString("// core-install <lang>` regenerates it from .mekami/config.json.\n")
	buf.WriteString("//\n")
	buf.WriteString("// The initial commit contains the Go frontend as a builtin so\n")
	buf.WriteString("// `mekami build` works on a Go project without any setup. To\n")
	buf.WriteString("// install additional languages, use `mekami core-install\n")
	buf.WriteString("// <lang>[@version]`; that command appends the new entry here\n")
	buf.WriteString("// and updates .mekami/config.json.\n")
	buf.WriteString("//\n")
	buf.WriteString("// Adding a language by hand is possible (add a blank import) but\n")
	buf.WriteString("// the next `core-install` will overwrite the file.\n")
	buf.WriteString("package all_gen\n\n")
	if len(cfgIndexers) == 0 {
		buf.WriteString("import ()\n")
		return buf.Bytes(), nil
	}
	names := make([]string, 0, len(cfgIndexers))
	for name := range cfgIndexers {
		names = append(names, name)
	}
	sort.Strings(names)
	buf.WriteString("import (\n")
	for _, name := range names {
		if !IsValidLang(name) {
			return nil, fmt.Errorf("config.indexers contains invalid language %q", name)
		}
		comment := name
		if v := cfgIndexers[name]; v != "" {
			comment = name + " @ " + v
		}
		fmt.Fprintf(&buf, "\t_ %q // %s\n", ModulePath(name), comment)
	}
	buf.WriteString(")\n")
	return buf.Bytes(), nil
}

// WriteAllGen regenerates all_gen.go at workDir/mekami-core/
// frontend/all_gen/all_gen.go from cfgIndexers. If the existing
// file already matches, WriteAllGen is a no-op. The function
// preserves the file's existing permissions.
func WriteAllGen(workDir string, cfgIndexers map[string]string) error {
	desired, err := GenerateAllGen(cfgIndexers)
	if err != nil {
		return err
	}
	path := AllGenPath(workDir)
	if existing, err := os.ReadFile(path); err == nil {
		if bytes.Equal(existing, desired) {
			return nil
		}
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("read %s: %w", path, err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir: %w", err)
	}
	if err := os.WriteFile(path, desired, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
