// Command dev-allgen rewrites the generated all_gen.go file with
// a hard-coded set of language frontends for the dev build.
//
// Usage:
//
//	go run ./mekami-core/scripts/dev-allgen <output-path>
//
// It writes the file at the given path, overwriting any existing
// content. The format matches what coreinstall.GenerateAllGen
// produces; the two are kept deliberately independent so this
// helper has no dependency on mekami-cli.
//
// The hard-coded set lives in devCores. To add a permanent
// builtin, edit the slice. Per-project indexers should be added
// via `mekami core-install <lang>` instead.
package main

import (
	"fmt"
	"os"
	"strings"
)

// devCores is the set of language frontends baked into the dev
// binary. Today only Go. Order does not matter; the output is
// sorted for stability.
var devCores = []string{
	"github.com/Wolf258/mekami-core-go",
}

// render produces the full source for all_gen.go given the list
// of import paths. The header documents the dev-vs-prod split.
func render(imports []string) string {
	var b strings.Builder
	b.WriteString("// Code generated by mekami dev-allgen; DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// This file is the single source of truth for the set of language\n")
	b.WriteString("// frontends the mekami binary blank-imports at startup. The dev\n")
	b.WriteString("// build script (build.sh) rewrites it on every build to ensure\n")
	b.WriteString("// the binary has Go as a builtin. The production release process\n")
	b.WriteString("// regenerates it from .mekami/config.json via `mekami core-install`.\n")
	b.WriteString("//\n")
	b.WriteString("// To add a permanent builtin, edit dev-allgen/devCores. To add a\n")
	b.WriteString("// per-project indexer, run `mekami core-install <lang>`.\n")
	b.WriteString("package all_gen\n\n")
	if len(imports) == 0 {
		b.WriteString("import ()\n")
		return b.String()
	}
	b.WriteString("import (\n")
	for _, p := range imports {
		fmt.Fprintf(&b, "\t_ %q\n", p)
	}
	b.WriteString(")\n")
	return b.String()
}

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintf(os.Stderr, "usage: dev-allgen <output-path>\n")
		os.Exit(64)
	}
	out := os.Args[1]
	sorted := append([]string(nil), devCores...)
	// Stable order: the slice is small; bubble sort keeps the
	// helper dependency-free.
	for i := 1; i < len(sorted); i++ {
		for j := i; j > 0 && sorted[j-1] > sorted[j]; j-- {
			sorted[j-1], sorted[j] = sorted[j], sorted[j-1]
		}
	}
	if err := os.WriteFile(out, []byte(render(sorted)), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "dev-allgen: write %s: %v\n", out, err)
		os.Exit(1)
	}
}
